from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase
from django.contrib.auth.models import User
from unittest.mock import patch
from management_app.models import Quiz


def _make_valid_payload():
    return {
        "title": "Stub Quiz",
        "description": "Generated by stub",
        "questions": [
            {
                "question_title": f"Q{i}",
                "question_options": [f"A{i}", f"B{i}", f"C{i}", f"D{i}"],
                "answer": f"A{i}",
            }
            for i in range(1, 11)
        ],
    }


class CreateQuizApiTests(APITestCase):
    def setUp(self):
        self.user = User.objects.create_user(username="tester", password="secret123")
        self.client.force_authenticate(user=self.user)
        self.url = reverse("create-quiz")

    def test_create_quiz_invalid_domain(self):
        res = self.client.post(self.url, {"url": "https://example.com/video"}, format="json")
        self.assertEqual(res.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("URL must be a YouTube link.", str(res.data))

    def test_create_quiz_invalid_video_id(self):
        res = self.client.post(self.url, {"url": "https://www.youtube.com/watch?v=123"}, format="json")
        self.assertEqual(res.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("Invalid YouTube video ID.", str(res.data))

    def test_requires_authentication(self):
        self.client.force_authenticate(user=None)
        res = self.client.post(self.url, {"url": "https://www.youtube.com/watch?v=abcdefghijk"}, format="json")
        self.assertEqual(res.status_code, status.HTTP_401_UNAUTHORIZED)

    @patch("management_app.api.serializers.build_quiz_stub", return_value=_make_valid_payload())
    def test_youtu_be_normalization_persisted(self, _mock_build):
        res = self.client.post(self.url, {"url": "https://youtu.be/abcdefghijk"}, format="json")
        self.assertEqual(res.status_code, status.HTTP_201_CREATED)
        quiz = Quiz.objects.first()
        self.assertEqual(quiz.video_url, "https://www.youtube.com/watch?v=abcdefghijk")
