"""
Utility functions for persisting quizzes generated by the AI pipeline.

Includes:
- persist_quiz: Saves a quiz and associated questions atomically.
- validate_payload: Ensures AI payload integrity (10 questions, 4 options each, valid answers).
"""

from django.db import transaction
from management_app.models import Quiz, Question
from management_app.services.error import AIPipelineError


@transaction.atomic
def persist_quiz(*, owner, video_url: str, payload: dict) -> Quiz:
    """
    Persist a quiz and its questions into the database.

    Steps:
    - Validate the AI-generated payload structure.
    - Create a Quiz instance.
    - Bulk-create Question instances.

    Parameters:
        owner (User): The user who owns the quiz.
        video_url (str): The source YouTube URL.
        payload (dict): The validated quiz data from the pipeline.

    Returns:
        Quiz: The newly created quiz instance.
    """
    validate_payload(payload)

    quiz = Quiz.objects.create(
        owner=owner,
        video_url=video_url,
        title=payload["title"],
        description=payload.get("description", "")
    )

    Question.objects.bulk_create([
        Question(
            quiz=quiz,
            question_title=q["question_title"],
            question_options=q["question_options"],
            answer=q["answer"],
        )
        for q in payload["questions"]
    ])

    return quiz


def validate_payload(payload: dict):
    """
    Validate the structure of the AI-generated quiz payload.

    Ensures:
    - Exactly 10 questions exist.
    - Each question has exactly 4 options.
    - The answer is one of the provided options.

    Raises:
        AIPipelineError: If the payload structure is invalid.
    """
    questions = payload.get("questions", [])

    if len(questions) != 10:
        raise AIPipelineError("AI pipeline failed: expected 10 questions")

    for i, q in enumerate(questions, start=1):
        options = q.get("question_options", [])
        if len(options) != 4:
            raise AIPipelineError(
                f"AI pipeline failed: question {i} has {len(options)} options"
            )

        if q.get("answer") not in options:
            raise AIPipelineError(
                f"AI pipeline failed: invalid answer in question {i}"
            )
