from django.db import transaction
from management_app.models import Quiz, Question
from management_app.services.error import AIPipelineError


@transaction.atomic
def persist_quiz(*, owner, video_url: str, payload: dict) -> Quiz:
    """
    Persist a new Quiz and its related Questions in the database.

    This function takes a validated quiz payload generated by the AI pipeline
    and creates both the Quiz object and all associated Question objects.
    The operation is atomic — if any error occurs during the creation process,
    all database changes are rolled back.

    Args:
        owner (User): The user who owns the quiz.
        video_url (str): The normalized YouTube video URL.
        payload (dict): The quiz data including title, description, and questions.

    Returns:
        Quiz: The created Quiz instance.

    Raises:
        AIPipelineError: If the provided payload fails validation.
    """
    validate_payload(payload)

    quiz = Quiz.objects.create(
        owner=owner,
        video_url=video_url,
        title=payload["title"],
        description=payload.get("description", "")
    )
    Question.objects.bulk_create([
        Question(
            quiz=quiz,
            question_title=q["question_title"],
            question_options=q["question_options"],
            answer=q["answer"],
        )
        for q in payload["questions"]
    ])
    return quiz


def validate_payload(payload: dict):
    """
    Validate the structure of the AI-generated quiz payload.

    Ensures that the payload contains exactly 10 questions, each with
    exactly four answer options, and that each question’s correct answer
    is included in its list of options.

    Args:
        payload (dict): The AI-generated quiz data to be validated.

    Raises:
        AIPipelineError: If the payload is malformed or incomplete.
    """
    questions = payload.get("questions", [])
    if len(questions) != 10:
        raise AIPipelineError("AI pipeline failed: expected 10 questions")

    for i, q in enumerate(questions, start=1):
        options = q.get("question_options", [])
        if len(options) != 4:
            raise AIPipelineError(f"AI pipeline failed: question {i} has {len(options)} options")
        if q.get("answer") not in options:
            raise AIPipelineError(f"AI pipeline failed: invalid answer in question {i}")